version: "3.8"

services:

  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
